In [7]:
import torch
# The train split of client 1
train_data_client1 = torch.load('./data/CIKM22Competition/1/train.pt')
# Check the first sample
print(train_data_client1[0])
# Check the label of the first sample
print(len(train_data_client1))
# Check the index of the first sample as ${sample_id}
print(train_data_client1[0].data_index)

Data(x=[43, 22], edge_index=[2, 98], edge_attr=[98, 8], y=[1, 1], data_index=0)
1249
0


In [8]:
ys = [train_data_client1[i].y for i in range(len(train_data_client1)-1)]

In [9]:
sum(ys)

tensor([[485]])

In [10]:
sum(ys) / len(ys)

tensor([[0.3886]])

In [11]:
1- sum(ys) / len(ys)

tensor([[0.6114]])

1: 1249
2: 181
3: 2219
4: 101
5: 188
6: 1101
7: 2228
8: 777
9: 134706
10: 109392
11: 2268
12: 608
13: 70648

1: 0
2: 0
3: 0
4:1
5:0
6:1
7:0

In [ ]:
import numpy as np

In [ ]:
a = [1249, 181, 2219, 101, 188, 1101, 2228, 777, 134706, 109392, 2268, 608, 70648]
a/np.array(sum(a))

In [ ]:
!python federatedscope/main.py --cfg federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup.yaml --client_cfg federatedscope/gfl/baseline/isolated_gin_minibatch_on_cikmcup_per_client.yaml federate.total_round_num 3


2022-09-13 12:39:32,796 (cfg_fl_setting:104)WARNING: In local/global training mode, the sampling related configs are in-valid, we will use all clients. 
2022-09-13 12:39:32,796 (cfg_fl_setting:104)WARNING: In local/global training mode, the sampling related configs are in-valid, we will use all clients. 
2022-09-13 12:39:32,797 (utils:129)INFO: the current machine is at 127.0.1.1
2022-09-13 12:39:32,797 (utils:131)INFO: the current dir is /home/michael/Master thesis/Code/FederatedScope_thesis
2022-09-13 12:39:32,797 (utils:132)INFO: the output dir is exp/local_gin_on_cikmcup_lr0.1_lstep21_/sub_exp_20220913123932
2022-09-13 12:39:32,888 (cikm_cup:57)INFO: Loading CIKMCUP data from /home/michael/Master thesis/Code/FederatedScope_thesis/data/CIKM22Competition.
2022-09-13 12:39:32,889 (cfg_fl_setting:104)WARNING: In local/global training mode, the sampling related configs are in-valid, we will use all clients. 
2022-09-13 12:39:32,889 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #1.


In [ ]:
del train_data_client1

In [1]:
!python federatedscope/main.py --cfg federatedscope/gfl/baseline/fedavg_gin_minibatch_on_cikmcup.yaml --client_cfg federatedscope/gfl/baseline/fedavg_gin_minibatch_on_cikmcup_per_client.yaml federate.total_round_num 3

2022-09-13 12:40:30,761 (utils:129)INFO: the current machine is at 127.0.1.1
2022-09-13 12:40:30,761 (utils:131)INFO: the current dir is /home/michael/Master thesis/Code/FederatedScope_thesis
2022-09-13 12:40:30,761 (utils:132)INFO: the output dir is exp/FedAvg_gin_on_cikmcup_lr0.1_lstep1_/sub_exp_20220913124030
2022-09-13 12:40:30,810 (cikm_cup:57)INFO: Loading CIKMCUP data from /home/michael/Master thesis/Code/FederatedScope_thesis/data/CIKM22Competition.
2022-09-13 12:40:30,810 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #1.
2022-09-13 12:40:30,998 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #2.
2022-09-13 12:40:31,012 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #3.
2022-09-13 12:40:31,255 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #4.
2022-09-13 12:40:31,262 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #5.
2022-09-13 12:40:31,277 (cikm_cup:67)INFO: Loading CIKMCUP data for Client #6.
2022-09-13 12:40:31,383 (cikm_cup:67)INFO: Loading CIKMCUP data 