In [1]:
from federatedscope.register import register_data
from federatedscope.register import register_trainer
from federatedscope.register import register_metric
from federatedscope.register import register_model

### Register data

In [2]:
from federatedscope.contrib.data.mnist_data import call_my_data

register_data("mydata", call_my_data)

### Register model

In [3]:
from federatedscope.contrib.model.mnist_model import call_my_net
register_model("mynet2", call_my_net)

### Register trainer

In [4]:
from federatedscope.contrib.trainer.laplacian_trainer_no_graph import call_laplacian_trainer

register_trainer('laplacian_trainer_no_graph', call_laplacian_trainer)

### Register metric

In [5]:
from federatedscope.contrib.metrics.mnist_metric import call_my_metric

register_metric("mymetric", call_my_metric)

### Create the config

#### Set data, model, trainer and metric

In [6]:
from federatedscope.core.configs.config import global_cfg, CN

cfg = global_cfg.clone()
cfg.data.type = 'mydata'
cfg.data.root = 'data'
cfg.data.transform = [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]
cfg.model.type = 'mynet2'
cfg.model.in_channels = 1
cfg.model.out_channels = 10
cfg.trainer.type = 'laplacian_trainer'
cfg.eval.metric = ['mymetric']

#### configure other options

In [7]:
cfg.use_gpu = True
cfg.best_res_update_round_wise_key = "test_loss"

cfg.federate.mode = 'standalone'
cfg.federate.local_update_steps = 1
cfg.federate.total_round_num = 2
cfg.federate.sample_client_num = 50
cfg.federate.client_num = 50

cfg.train.optimizer.lr = 0.1
cfg.train.optimizer.weight_decay = 0.0
cfg.grad.grad_clip = 5.0
cfg.train.local_update_steps = 5
cfg.train.batch_or_epoch = 'epoch'
cfg.criterion.type = 'CrossEntropyLoss'
cfg.seed = 123
cfg.eval.best_res_update_round_wise_key = "test_loss"
cfg.params = CN()
cfg.params.alpha=0.01
cfg.params.csd_importance=0
cfg.params.eps=1e-5
cfg.params.p=0.
cfg.eval.metrics = ['acc']

### Start the FL prosess

In [8]:
from federatedscope.core.auxiliaries.data_builder import get_data
from federatedscope.core.auxiliaries.utils import setup_seed, update_logger
from federatedscope.core.fed_runner import FedRunner
from federatedscope.core.auxiliaries.worker_builder import get_server_cls, get_client_cls


2022-09-06 21:21:28,404 (register:12)WARNING: Key mydata is already pre-defined, overwritten.


In [9]:
from federatedscope.contrib.workers.laplacian_client_no_graph import LaplacianClient
from federatedscope.contrib.workers.laplacian_server import LaplacianServer

In [10]:

setup_seed(cfg.seed)
update_logger(cfg)
data, modified_cfg = get_data(cfg)
cfg.merge_from_other_cfg(modified_cfg)


2022-09-06 21:21:28,441 (utils:129)INFO: the current machine is at 127.0.1.1
2022-09-06 21:21:28,442 (utils:131)INFO: the current dir is /home/michael/Master thesis/Code/FederatedScope_thesis
2022-09-06 21:21:28,442 (utils:132)INFO: the output dir is exp/FedAvg_mynet2_on_mydata_lr0.1_lstep5_/sub_exp_20220906212128


In [11]:
from federatedscope.contrib.data.mnist_data import call_my_data

register_data("mydata", call_my_data)

2022-09-06 21:21:28,453 (register:12)WARNING: Key mydata is already pre-defined, overwritten.


In [12]:

setup_seed(cfg.seed)
update_logger(cfg)
data, modified_cfg = get_data(cfg)
cfg.merge_from_other_cfg(modified_cfg)


2022-09-06 21:21:28,467 (utils:129)INFO: the current machine is at 127.0.1.1
2022-09-06 21:21:28,467 (utils:131)INFO: the current dir is /home/michael/Master thesis/Code/FederatedScope_thesis
2022-09-06 21:21:28,468 (utils:132)INFO: the output dir is exp/FedAvg_mynet2_on_mydata_lr0.1_lstep5_/sub_exp_20220906212128/FedAvg_mynet2_on_mydata_lr0.1_lstep5__


train per client: 20


In [13]:
Fed_runner = FedRunner(data=data,
                       server_class=LaplacianServer,
                       client_class=LaplacianClient,
                       config=cfg.clone())
Fed_runner.run()

2022-09-06 21:21:32,667 (fed_runner:249)INFO: Server #0 has been set up ... 
2022-09-06 21:21:32,760 (trainer:50)WARNING: Will not use monitor in trainer with class <class 'federatedscope.contrib.trainer.laplacian_trainer_no_graph.LaplacianTrainerNoGraph'>
2022-09-06 21:21:32,761 (fed_runner:302)INFO: Client 1 has been set up ... 
2022-09-06 21:21:32,850 (trainer:50)WARNING: Will not use monitor in trainer with class <class 'federatedscope.contrib.trainer.laplacian_trainer_no_graph.LaplacianTrainerNoGraph'>
2022-09-06 21:21:32,851 (fed_runner:302)INFO: Client 2 has been set up ... 
2022-09-06 21:21:32,943 (trainer:50)WARNING: Will not use monitor in trainer with class <class 'federatedscope.contrib.trainer.laplacian_trainer_no_graph.LaplacianTrainerNoGraph'>
2022-09-06 21:21:32,945 (fed_runner:302)INFO: Client 3 has been set up ... 
2022-09-06 21:21:33,031 (trainer:50)WARNING: Will not use monitor in trainer with class <class 'federatedscope.contrib.trainer.laplacian_trainer_no_graph.L

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:38,475 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #19', 'Round': 0, 'Results_raw': {'train_loss': 180.888035, 'train_acc': 0.4, 'train_total': 100, 'train_avg_loss': 1.80888}}
2022-09-06 21:21:38,522 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #1', 'Round': 0, 'Results_raw': {'train_loss': 204.513302, 'train_acc': 0.27, 'train_total': 100, 'train_avg_loss': 2.045133}}
2022-09-06 21:21:38,566 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #41', 'Round': 0, 'Results_raw': {'train_loss': 184.833093, 'train_acc': 0.46, 'train_total': 100, 'train_avg_loss': 1.848331}}
2022-09-06 21:21:38,609 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #13', 'Round': 0, 'Results_raw': {'train_loss': 201.7327, 'train_acc': 0.23, 'train_total': 100, 'train_avg_loss': 2.017327}}
2022-09-06 21:21:38,650 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #30', 'Round': 0, 'Results_raw': {'train_loss': 197.493563, 'train_acc': 0.27, 'train_total': 100, 'tra

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:38,694 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #9', 'Round': 0, 'Results_raw': {'train_loss': 193.833861, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 1.938339}}
2022-09-06 21:21:38,736 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #22', 'Round': 0, 'Results_raw': {'train_loss': 184.683781, 'train_acc': 0.42, 'train_total': 100, 'train_avg_loss': 1.846838}}
2022-09-06 21:21:38,778 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #48', 'Round': 0, 'Results_raw': {'train_loss': 190.486474, 'train_acc': 0.38, 'train_total': 100, 'train_avg_loss': 1.904865}}
2022-09-06 21:21:38,820 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #12', 'Round': 0, 'Results_raw': {'train_loss': 204.180372, 'train_acc': 0.41, 'train_total': 100, 'train_avg_loss': 2.041804}}


tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:38,862 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #42', 'Round': 0, 'Results_raw': {'train_loss': 193.851736, 'train_acc': 0.58, 'train_total': 100, 'train_avg_loss': 1.938517}}
2022-09-06 21:21:38,898 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #6', 'Round': 0, 'Results_raw': {'train_loss': 186.094689, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.860947}}
2022-09-06 21:21:38,945 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #2', 'Round': 0, 'Results_raw': {'train_loss': 203.685467, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 2.036855}}
2022-09-06 21:21:38,988 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #7', 'Round': 0, 'Results_raw': {'train_loss': 203.179989, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 2.0318}}
2022-09-06 21:21:39,027 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #28', 'Round': 0, 'Results_raw': {'train_loss': 195.319047, 'train_acc': 0.36, 'train_total': 100, 'tra

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:39,076 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #50', 'Round': 0, 'Results_raw': {'train_loss': 194.152062, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.941521}}
2022-09-06 21:21:39,119 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #25', 'Round': 0, 'Results_raw': {'train_loss': 201.219862, 'train_acc': 0.36, 'train_total': 100, 'train_avg_loss': 2.012199}}
2022-09-06 21:21:39,164 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #32', 'Round': 0, 'Results_raw': {'train_loss': 188.437347, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.884373}}
2022-09-06 21:21:39,210 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #16', 'Round': 0, 'Results_raw': {'train_loss': 191.805561, 'train_acc': 0.42, 'train_total': 100, 'train_avg_loss': 1.918056}}
2022-09-06 21:21:39,249 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #36', 'Round': 0, 'Results_raw': {'train_loss': 202.67719, 'train_acc': 0.4, 'train_total': 100, '

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:39,290 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #27', 'Round': 0, 'Results_raw': {'train_loss': 191.305037, 'train_acc': 0.46, 'train_total': 100, 'train_avg_loss': 1.91305}}
2022-09-06 21:21:39,330 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #8', 'Round': 0, 'Results_raw': {'train_loss': 202.205572, 'train_acc': 0.33, 'train_total': 100, 'train_avg_loss': 2.022056}}
2022-09-06 21:21:39,373 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #21', 'Round': 0, 'Results_raw': {'train_loss': 196.963456, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 1.969635}}
2022-09-06 21:21:39,416 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #49', 'Round': 0, 'Results_raw': {'train_loss': 193.024478, 'train_acc': 0.44, 'train_total': 100, 'train_avg_loss': 1.930245}}
2022-09-06 21:21:39,453 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #4', 'Round': 0, 'Results_raw': {'train_loss': 180.71805, 'train_acc': 0.45, 'train_total': 100, 'tr

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:39,499 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #24', 'Round': 0, 'Results_raw': {'train_loss': 199.684453, 'train_acc': 0.45, 'train_total': 100, 'train_avg_loss': 1.996845}}
2022-09-06 21:21:39,546 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #45', 'Round': 0, 'Results_raw': {'train_loss': 190.539589, 'train_acc': 0.33, 'train_total': 100, 'train_avg_loss': 1.905396}}
2022-09-06 21:21:39,591 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #5', 'Round': 0, 'Results_raw': {'train_loss': 192.778594, 'train_acc': 0.49, 'train_total': 100, 'train_avg_loss': 1.927786}}
2022-09-06 21:21:39,634 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #17', 'Round': 0, 'Results_raw': {'train_loss': 192.373354, 'train_acc': 0.55, 'train_total': 100, 'train_avg_loss': 1.923734}}


tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:39,681 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #37', 'Round': 0, 'Results_raw': {'train_loss': 183.627539, 'train_acc': 0.43, 'train_total': 100, 'train_avg_loss': 1.836275}}
2022-09-06 21:21:39,728 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #15', 'Round': 0, 'Results_raw': {'train_loss': 188.32423, 'train_acc': 0.47, 'train_total': 100, 'train_avg_loss': 1.883242}}
2022-09-06 21:21:39,771 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #44', 'Round': 0, 'Results_raw': {'train_loss': 193.930895, 'train_acc': 0.28, 'train_total': 100, 'train_avg_loss': 1.939309}}
2022-09-06 21:21:39,815 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #26', 'Round': 0, 'Results_raw': {'train_loss': 191.501474, 'train_acc': 0.36, 'train_total': 100, 'train_avg_loss': 1.915015}}
2022-09-06 21:21:39,861 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #38', 'Round': 0, 'Results_raw': {'train_loss': 192.380581, 'train_acc': 0.58, 'train_total': 100, 

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:39,902 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #40', 'Round': 0, 'Results_raw': {'train_loss': 189.409111, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.894091}}
2022-09-06 21:21:39,944 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #10', 'Round': 0, 'Results_raw': {'train_loss': 191.875093, 'train_acc': 0.3, 'train_total': 100, 'train_avg_loss': 1.918751}}
2022-09-06 21:21:39,991 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #33', 'Round': 0, 'Results_raw': {'train_loss': 194.368553, 'train_acc': 0.4, 'train_total': 100, 'train_avg_loss': 1.943686}}
2022-09-06 21:21:40,032 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #34', 'Round': 0, 'Results_raw': {'train_loss': 186.095407, 'train_acc': 0.3, 'train_total': 100, 'train_avg_loss': 1.860954}}
2022-09-06 21:21:40,079 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #23', 'Round': 0, 'Results_raw': {'train_loss': 187.098501, 'train_acc': 0.4, 'train_total': 100, 'tr

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:40,118 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #43', 'Round': 0, 'Results_raw': {'train_loss': 199.548304, 'train_acc': 0.31, 'train_total': 100, 'train_avg_loss': 1.995483}}
2022-09-06 21:21:40,153 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #20', 'Round': 0, 'Results_raw': {'train_loss': 195.604627, 'train_acc': 0.27, 'train_total': 100, 'train_avg_loss': 1.956046}}
2022-09-06 21:21:40,202 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #18', 'Round': 0, 'Results_raw': {'train_loss': 185.2354, 'train_acc': 0.45, 'train_total': 100, 'train_avg_loss': 1.852354}}
2022-09-06 21:21:40,241 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #39', 'Round': 0, 'Results_raw': {'train_loss': 185.952175, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 1.859522}}
2022-09-06 21:21:40,291 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #35', 'Round': 0, 'Results_raw': {'train_loss': 199.525018, 'train_acc': 0.33, 'train_total': 100, '

tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], devic

2022-09-06 21:21:40,333 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #29', 'Round': 0, 'Results_raw': {'train_loss': 204.869101, 'train_acc': 0.36, 'train_total': 100, 'train_avg_loss': 2.048691}}
2022-09-06 21:21:40,372 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #3', 'Round': 0, 'Results_raw': {'train_loss': 194.131787, 'train_acc': 0.29, 'train_total': 100, 'train_avg_loss': 1.941318}}
2022-09-06 21:21:40,422 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #46', 'Round': 0, 'Results_raw': {'train_loss': 200.069475, 'train_acc': 0.32, 'train_total': 100, 'train_avg_loss': 2.000695}}
2022-09-06 21:21:40,495 (laplacian_server:143)INFO: Server #0: Starting evaluation at the end of round 0.
2022-09-06 21:21:40,497 (laplacian_server:150)INFO: ----------- Starting a new training round (Round #1) -------------


tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04,

2022-09-06 21:21:41,273 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #5', 'Round': 1, 'Results_raw': {'train_loss': 157.205372, 'train_acc': 0.53, 'train_total': 100, 'train_avg_loss': 1.572054}}
2022-09-06 21:21:41,312 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #6', 'Round': 1, 'Results_raw': {'train_loss': 159.738727, 'train_acc': 0.63, 'train_total': 100, 'train_avg_loss': 1.597387}}


tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:41,360 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #1', 'Round': 1, 'Results_raw': {'train_loss': 185.947978, 'train_acc': 0.43, 'train_total': 100, 'train_avg_loss': 1.85948}}
2022-09-06 21:21:41,406 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #38', 'Round': 1, 'Results_raw': {'train_loss': 175.107415, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.751074}}
2022-09-06 21:21:41,452 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #24', 'Round': 1, 'Results_raw': {'train_loss': 170.713754, 'train_acc': 0.5, 'train_total': 100, 'train_avg_loss': 1.707138}}
2022-09-06 21:21:41,494 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #11', 'Round': 1, 'Results_raw': {'train_loss': 149.716433, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.497164}}
2022-09-06 21:21:41,526 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #46', 'Round': 1, 'Results_raw': {'train_loss': 184.969573, 'train_acc': 0.39, 'train_total': 100, 't

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:41,573 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #41', 'Round': 1, 'Results_raw': {'train_loss': 152.082545, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.520825}}
2022-09-06 21:21:41,619 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #39', 'Round': 1, 'Results_raw': {'train_loss': 183.309581, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.833096}}
2022-09-06 21:21:41,662 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #9', 'Round': 1, 'Results_raw': {'train_loss': 187.448719, 'train_acc': 0.38, 'train_total': 100, 'train_avg_loss': 1.874487}}
2022-09-06 21:21:41,705 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #32', 'Round': 1, 'Results_raw': {'train_loss': 165.460036, 'train_acc': 0.49, 'train_total': 100, 'train_avg_loss': 1.6546}}


tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:41,749 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #49', 'Round': 1, 'Results_raw': {'train_loss': 169.029608, 'train_acc': 0.55, 'train_total': 100, 'train_avg_loss': 1.690296}}
2022-09-06 21:21:41,797 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #33', 'Round': 1, 'Results_raw': {'train_loss': 168.007009, 'train_acc': 0.45, 'train_total': 100, 'train_avg_loss': 1.68007}}
2022-09-06 21:21:41,847 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #29', 'Round': 1, 'Results_raw': {'train_loss': 170.952806, 'train_acc': 0.41, 'train_total': 100, 'train_avg_loss': 1.709528}}
2022-09-06 21:21:41,893 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #3', 'Round': 1, 'Results_raw': {'train_loss': 176.793301, 'train_acc': 0.39, 'train_total': 100, 'train_avg_loss': 1.767933}}
2022-09-06 21:21:41,945 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #50', 'Round': 1, 'Results_raw': {'train_loss': 163.043084, 'train_acc': 0.52, 'train_total': 100, '

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:41,983 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #36', 'Round': 1, 'Results_raw': {'train_loss': 161.187294, 'train_acc': 0.5, 'train_total': 100, 'train_avg_loss': 1.611873}}
2022-09-06 21:21:42,031 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #47', 'Round': 1, 'Results_raw': {'train_loss': 159.243658, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.592437}}
2022-09-06 21:21:42,080 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #34', 'Round': 1, 'Results_raw': {'train_loss': 169.888973, 'train_acc': 0.49, 'train_total': 100, 'train_avg_loss': 1.69889}}
2022-09-06 21:21:42,124 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #4', 'Round': 1, 'Results_raw': {'train_loss': 161.412445, 'train_acc': 0.56, 'train_total': 100, 'train_avg_loss': 1.614124}}


tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:42,173 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #45', 'Round': 1, 'Results_raw': {'train_loss': 183.840401, 'train_acc': 0.44, 'train_total': 100, 'train_avg_loss': 1.838404}}
2022-09-06 21:21:42,215 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #40', 'Round': 1, 'Results_raw': {'train_loss': 153.488426, 'train_acc': 0.47, 'train_total': 100, 'train_avg_loss': 1.534884}}
2022-09-06 21:21:42,259 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #10', 'Round': 1, 'Results_raw': {'train_loss': 178.656342, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.786563}}
2022-09-06 21:21:42,307 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #22', 'Round': 1, 'Results_raw': {'train_loss': 162.930026, 'train_acc': 0.4, 'train_total': 100, 'train_avg_loss': 1.6293}}
2022-09-06 21:21:42,346 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #30', 'Round': 1, 'Results_raw': {'train_loss': 163.812747, 'train_acc': 0.54, 'train_total': 100, 't

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:42,399 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #20', 'Round': 1, 'Results_raw': {'train_loss': 182.945797, 'train_acc': 0.51, 'train_total': 100, 'train_avg_loss': 1.829458}}
2022-09-06 21:21:42,439 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #35', 'Round': 1, 'Results_raw': {'train_loss': 181.745901, 'train_acc': 0.34, 'train_total': 100, 'train_avg_loss': 1.817459}}
2022-09-06 21:21:42,476 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #43', 'Round': 1, 'Results_raw': {'train_loss': 168.230915, 'train_acc': 0.47, 'train_total': 100, 'train_avg_loss': 1.682309}}
2022-09-06 21:21:42,522 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #48', 'Round': 1, 'Results_raw': {'train_loss': 175.429511, 'train_acc': 0.43, 'train_total': 100, 'train_avg_loss': 1.754295}}
2022-09-06 21:21:42,570 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #13', 'Round': 1, 'Results_raw': {'train_loss': 181.51844, 'train_acc': 0.43, 'train_total': 100, 

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:42,620 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #18', 'Round': 1, 'Results_raw': {'train_loss': 162.991006, 'train_acc': 0.47, 'train_total': 100, 'train_avg_loss': 1.62991}}
2022-09-06 21:21:42,667 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #25', 'Round': 1, 'Results_raw': {'train_loss': 181.612086, 'train_acc': 0.37, 'train_total': 100, 'train_avg_loss': 1.816121}}
2022-09-06 21:21:42,713 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #21', 'Round': 1, 'Results_raw': {'train_loss': 183.13508, 'train_acc': 0.43, 'train_total': 100, 'train_avg_loss': 1.831351}}
2022-09-06 21:21:42,754 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #26', 'Round': 1, 'Results_raw': {'train_loss': 180.494337, 'train_acc': 0.39, 'train_total': 100, 'train_avg_loss': 1.804943}}


tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:42,801 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #2', 'Round': 1, 'Results_raw': {'train_loss': 171.105185, 'train_acc': 0.41, 'train_total': 100, 'train_avg_loss': 1.711052}}
2022-09-06 21:21:42,849 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #8', 'Round': 1, 'Results_raw': {'train_loss': 177.740633, 'train_acc': 0.51, 'train_total': 100, 'train_avg_loss': 1.777406}}
2022-09-06 21:21:42,891 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #12', 'Round': 1, 'Results_raw': {'train_loss': 174.282212, 'train_acc': 0.46, 'train_total': 100, 'train_avg_loss': 1.742822}}
2022-09-06 21:21:42,948 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #15', 'Round': 1, 'Results_raw': {'train_loss': 162.075005, 'train_acc': 0.44, 'train_total': 100, 'train_avg_loss': 1.62075}}
2022-09-06 21:21:42,998 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #42', 'Round': 1, 'Results_raw': {'train_loss': 167.704859, 'train_acc': 0.51, 'train_total': 100, 't

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:43,041 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #17', 'Round': 1, 'Results_raw': {'train_loss': 162.759352, 'train_acc': 0.58, 'train_total': 100, 'train_avg_loss': 1.627594}}
2022-09-06 21:21:43,088 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #27', 'Round': 1, 'Results_raw': {'train_loss': 159.987533, 'train_acc': 0.48, 'train_total': 100, 'train_avg_loss': 1.599875}}
2022-09-06 21:21:43,133 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #7', 'Round': 1, 'Results_raw': {'train_loss': 167.277434, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.672774}}
2022-09-06 21:21:43,184 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #31', 'Round': 1, 'Results_raw': {'train_loss': 178.120062, 'train_acc': 0.39, 'train_total': 100, 'train_avg_loss': 1.781201}}


tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:43,230 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #28', 'Round': 1, 'Results_raw': {'train_loss': 187.072773, 'train_acc': 0.3, 'train_total': 100, 'train_avg_loss': 1.870728}}
2022-09-06 21:21:43,281 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #44', 'Round': 1, 'Results_raw': {'train_loss': 163.122461, 'train_acc': 0.41, 'train_total': 100, 'train_avg_loss': 1.631225}}
2022-09-06 21:21:43,327 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #16', 'Round': 1, 'Results_raw': {'train_loss': 162.399695, 'train_acc': 0.44, 'train_total': 100, 'train_avg_loss': 1.623997}}
2022-09-06 21:21:43,362 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #37', 'Round': 1, 'Results_raw': {'train_loss': 164.805214, 'train_acc': 0.54, 'train_total': 100, 'train_avg_loss': 1.648052}}
2022-09-06 21:21:43,405 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #19', 'Round': 1, 'Results_raw': {'train_loss': 175.022957, 'train_acc': 0.38, 'train_total': 100, 

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
 

2022-09-06 21:21:43,452 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #14', 'Round': 1, 'Results_raw': {'train_loss': 179.796233, 'train_acc': 0.39, 'train_total': 100, 'train_avg_loss': 1.797962}}
2022-09-06 21:21:43,499 (laplacian_client_no_graph:118)INFO: {'Role': 'Client #23', 'Round': 1, 'Results_raw': {'train_loss': 154.050782, 'train_acc': 0.52, 'train_total': 100, 'train_avg_loss': 1.540508}}
2022-09-06 21:21:43,503 (server:480)INFO: {'Role': 'Server #', 'Round': 1, 'Results_weighted_avg': {'test_loss': 419.255437, 'test_acc': 0.3737, 'test_total': 200.0, 'test_avg_loss': 2.096277}, 'Results_avg': {'test_loss': 419.255437, 'test_acc': 0.3737, 'test_total': 200.0, 'test_avg_loss': 2.096277}, 'Results_fairness': {'test_total': 200.0, 'test_loss_std': 13.493339, 'test_loss_bottom_decile': 402.526579, 'test_loss_top_decile': 437.361566, 'test_acc_std': 0.036631, 'test_acc_bottom_decile': 0.325, 'test_acc_top_decile': 0.42, 'test_avg_loss_std': 0.067467, 'test_avg_loss_botto

tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([1.0441e-04, 1.2662e-04, 9.1113e-05, 8.2974e-05, 4.8273e-05],
       device='cuda:0')
tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')
tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')
tensor([0.0003, 0.0003, 0.0002,

2022-09-06 21:21:44,273 (server:480)INFO: {'Role': 'Server #', 'Round': 2, 'Results_weighted_avg': {'test_loss': 303.091103, 'test_acc': 0.6951, 'test_total': 200.0, 'test_avg_loss': 1.515456}, 'Results_avg': {'test_loss': 303.091103, 'test_acc': 0.6951, 'test_total': 200.0, 'test_avg_loss': 1.515456}, 'Results_fairness': {'test_total': 200.0, 'test_loss_std': 19.221527, 'test_loss_bottom_decile': 281.063826, 'test_loss_top_decile': 325.030019, 'test_acc_std': 0.052311, 'test_acc_bottom_decile': 0.63, 'test_acc_top_decile': 0.76, 'test_avg_loss_std': 0.096108, 'test_avg_loss_bottom_decile': 1.405319, 'test_avg_loss_top_decile': 1.62515}}
2022-09-06 21:21:44,275 (server:379)INFO: Server #0: Final evaluation is finished! Starting merging results.
2022-09-06 21:21:44,276 (server:409)INFO: {'Role': 'Server #', 'Round': 'Final', 'Results_raw': {'client_best_individual': {'test_loss': 258.939436, 'test_acc': 0.6, 'test_total': 200.0, 'test_avg_loss': 1.294697}, 'client_summarized_weighted_av

tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')
tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')
tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')
tensor([0.0003, 0.0003, 0.0002, 0.0002, 0.0001], device='cuda:0')


{'client_best_individual': {'test_loss': 258.9394359588623,
  'test_acc': 0.6,
  'test_total': 200.0,
  'test_avg_loss': 1.2946971797943114},
 'client_summarized_weighted_avg': {'test_loss': 303.09110340118406,
  'test_acc': 0.6951,
  'test_total': 200.0,
  'test_avg_loss': 1.5154555170059205},
 'client_summarized_avg': {'test_loss': 303.09110340118406,
  'test_acc': 0.6950999999999999,
  'test_total': 200.0,
  'test_avg_loss': 1.5154555170059203},
 'client_summarized_fairness': {'test_loss_top_decile': 325.0300188064575,
  'test_loss_bottom_decile': 281.0638256072998,
  'test_loss_std': 19.221526965696587,
  'test_total': 200.0,
  'test_acc_std': 0.052311471017359085,
  'test_acc_bottom_decile': 0.63,
  'test_acc_top_decile': 0.76,
  'test_avg_loss_std': 0.0961076348284829,
  'test_avg_loss_bottom_decile': 1.405319128036499,
  'test_avg_loss_top_decile': 1.6251500940322876}}

In [14]:
data

{1: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192df18b0>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192df16a0>},
 2: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee760>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee670>},
 3: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee5e0>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee2b0>},
 4: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee160>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192dee310>},
 5: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192decee0>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192dec970>},
 6: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192dec820>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7f1192dec6a0>},
 7: {'train': <torch.utils.data.dataloader.DataLoader at 0x7f1192dec460>,
  'test': <torch.utils.data.dataloader.DataLoader at 0x7

In [15]:
cfg

CN({'backend': 'torch', 'use_gpu': True, 'verbose': 1, 'print_decimal_digits': 6, 'device': -1, 'seed': 123, 'cfg_file': '', 'outdir': 'exp/FedAvg_mynet2_on_mydata_lr0.1_lstep5_/sub_exp_20220906195741/FedAvg_mynet2_on_mydata_lr0.1_lstep5__', 'expname': 'FedAvg_mynet2_on_mydata_lr0.1_lstep5__', 'expname_tag': '', 'hpo': CN({'working_folder': 'hpo', 'ss': '', 'num_workers': 0, 'init_cand_num': 16, 'log_scale': False, 'larger_better': False, 'scheduler': 'rs', 'plot_interval': 1, 'metric': 'client_summarized_weighted_avg.val_loss', 'sha': CN({'elim_round_num': 3, 'elim_rate': 3, 'budgets': []}), 'pbt': CN({'max_stage': 5, 'perf_threshold': 0.1}), 'fedex': CN({'use': False, 'ss': '', 'flatten_ss': True, 'eta0': -1.0, 'sched': 'auto', 'cutoff': 0.0, 'gamma': 0.0, 'num_arms': 16, 'diff': False}), 'table': CN({'ss': '', 'eps': 0.1, 'num': 27, 'idx': 0})}), 'data': CN({'root': 'data', 'type': 'mydata', 'args': [], 'splitter': '', 'splitter_args': [], 'transform': [['ToTensor'], ['Normalize', {

In [ ]:
data

In [ ]:
from federatedscope.contrib.model.mnist_model import MyNet

model = MyNet(0)